config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'items/index', to: "items#index", as: "items_index"
  get 'items/:id/show', to: "items#show", as: "items_show"
  get 'items/filter', to: "items#filter", as: "items_filter"

  get 'carts/show'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: 'users/registrations' }

  resource :users do
    resources :orders, only: %i[new create index show]
  end

  devise_for :admins, controllers: { sessions: 'admins/sessions', confirmations: 'admins/confirmations', registrations: 'admins/registrations', passwords: 'admins/passwords', unlocks: 'admins/unlocks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  post 'cart_items/:item_id', to: "cart_items#create", as: "cart_items"
  delete 'cart_items/:id', to: "cart_items#destroy", as: "cart_items_destroy"
  post 'cart_items/:id/add_quantity', to: "cart_items#add_quantity", as: "cart_items_add"
  post 'cart_items/:id/reduce_quantity', to: "cart_items#reduce_quantity", as: "cart_items_reduce"
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :administration, only: [:index]

  namespace 'administration' do
    resources :items, only: %i[index create new destroy update edit]
    resources :orders, only: %i[index update edit show]
  end
end

app/views/shared/_cart.html.erb
<ul class="dropdown-menu dropdown-menu--right px-0">
    <li>
        <div class="dropdown-cart px-0">
            <div class="dc-header">
                <h3 class="heading heading-6 strong-600">Cart</h3>
            </div>
            <%@current_cart.cart_items.each do |cart_item|%>
            <div class="dc-item", id="<%=cart_item.id%>">
                <div class="d-flex align-items-center">
                    <div class="dc-image">
                      <%=image_tag cart_item.item.image_url, id: 'image_id'%>
                    </div>
                    <div class="dc-content">
                        <span class="d-block dc-product-name text-capitalize strong-600 mb-1">
                          <%=link_to "#{cart_item.item.name}", items_show_path(cart_item.item.id)%>
                        </span>
                        <span class="dc-quantity">x<%=cart_item.quantity%></span>
                        <span class="dc-price"><%=number_to_currency(cart_item.item.price, unit:'$')%></span>
                    </div>
                </div>
            </div>
            <%end%>
            <div class="dc-item py-4">
                <span class="subtotal-text">Total</span>
                <span class="subtotal-amount"><%=number_to_currency(@current_cart.tot, unit:'$')%></span>
            </div>
            <div class="py-4 text-center">
                <ul class="inline-links inline-links--style-3">
                    <li class="pr-3">
                        <a href="#" class="link link--style-2 text-capitalize">
                            <i class="ion-person"></i> My account
                        </a>
                    </li>
                    <li class="pr-3">
                        <a href="#" class="link link--style-1 text-capitalize">
                            <i class="ion-bag"></i> View cart
                        </a>
                    </li>
                    <li>
                        <a href="#" class="link link--style-1 text-capitalize">
                            <i class="ion-forward"></i> Checkout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </li>
</ul>

app/views/shared/_flash_messages.html.erb
<div id="flash" class="container-fluid">
<% if notice %>
	<div class="alert alert-success p-2 container">
		<%= notice %>
	</div>
<% elsif alert %>
	<div class="alert alert-danger p-2 container">
		<%= alert %>
	</div>
<% end %>
</div>

app/views/shared/_footer.html.erb
<!-- FOOTER -->
<footer id="footer" class="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row cols-xs-space cols-sm-space cols-md-space">
                <div class="col-lg-5">
                    <div class="col">
                        <a class="navbar-brand" href="/">
                                    <h3>😈</h3>
                        </a>
                        <span class="clearfix"></span>
                        <span class="heading heading-sm c-gray-light strong-400">One template. Infinite solutions.</span>
                        <p class="mt-3">
                            All the components included in Boomerang are built to the same level of quality as Bootstrap and highlighted with several example pages.
                        </p>
                        <div class="copyright mt-4">
                            <p>
                                Copyright &copy; 2018 <a href="https://webpixels.io" target="_blank">
                                    <strong>Webpixels</strong>
                                </a> -
                                All rights reserved
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
</div>
</div>
</div><!-- END: st-pusher -->
</div>
</div><!-- END: body-wrap -->
<!-- SCRIPTS -->
<a href="#" class="back-to-top btn-back-to-top"></a>

app/views/shared/_header.html.erb
<!-- MAIN WRAPPER -->
<div class="body-wrap shop-default shop-sportswear">
    <div id="st-container" class="st-container">
        <div class="st-pusher">
            <div class="st-content">
                <div class="st-content-inner">
                    <!-- Header -->
                    <div class="header">
                        <!-- Top Bar -->
                        <!-- Global Search -->
                        <section id="sctGlobalSearch" class="global-search global-search-overlay">
                            <div class="container">
                                <div class="global-search-backdrop mask-dark--style-2"></div>
                                <!-- Search form -->
                                <form class="form-horizontal form-global-search z-depth-2-top" role="form">
                                    <div class="px-4">
                                        <div class="row">
                                            <div class="col-12">
                                                <input type="text" class="search-input" placeholder="Type and hit enter ...">
                                            </div>
                                        </div>
                                    </div>
                                    <a href="#" class="close-search" data-toggle="global-search" title="Close search bar"></a>
                                </form>
                            </div>
                        </section>
                        <!-- Navbar -->
                        <nav class="navbar navbar-expand-lg navbar--bold navbar--style-2 navbar-light bg-default  navbar--bb-1px">
                            <div class="container navbar-container">
                                <!-- Brand/Logo -->
                                <a class="navbar-brand" href="/">
                                    <h3>😈</h3>
                                </a>
                                <div class="d-inline-block">
                                    <!-- Navbar toggler  -->
                                    <button class="navbar-toggler hamburger hamburger-js hamburger--spring" type="button" data-toggle="collapse" data-target="#navbar_main" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="hamburger-box">
                                        <span class="hamburger-inner"></span>
                                    </span>
                                    </button>
                                </div>
                                <div class="collapse navbar-collapse align-items-center justify-content-center" id="navbar_main">
                                    <!-- Navbar search - For small resolutions -->
                                    <div class="navbar-search-widget b-xs-bottom py-3 d-lg-none d-none">
                                        <form class="" role="form">
                                            <div class="input-group input-group-lg">
                                                <input type="text" class="form-control" placeholder="Search for...">
                                                <span class="input-group-btn">
                                                    <button class="btn btn-base-3" type="button">Go!</button>
                                                </span>
                                            </div>
                                        </form>
                                    </div>
                                    <!-- Navbar links -->
                                    <ul class="navbar-nav">
                                        <li class="nav-item">
                                            
                                        <%= link_to('Shop', items_index_path, class: "nav-link" )  %>  
                                       

                                        </li>
                                    </ul>
                                    <ul class="navbar-nav ml-lg-auto">
                                        <li class="nav-item">
                                            <a href="/item" class="nav-link">
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class=" d-none d-lg-inline-block d-xl-inline-block">
                                    <ul class="navbar-nav ml-auto" data-hover="dropdown">
                                        <!-- Search button -->
                                        
                                        <!-- Login try 2-->
                                            <% if user_signed_in? %>
                                        <li class="nav-item">
                                             <%= link_to "Your orders", users_orders_path, class:"nav-link"%>
                                        </li>
                                        <li class="nav-item">
                                             <%= link_to "Edit account", edit_user_registration_path(current_user.id), class:"nav-link"%>
                                        </li>
                                        <li class="nav-item">
                                            <%= link_to "Log out", destroy_user_session_path, class:"nav-link", method: :delete %>
                                        </li>
                                            <% else %>
                                        <li class="nav-item">
                                            <a href="/users/sign_in" class="nav-link">
                                                Sign in
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a href="/users/sign_up" class="nav-link">
                                                Sign up
                                            </a>
                                        </li>
                                            <% end %>
                                            
                                        </li>
                                        <!-- Cart -->
                                        <% if user_signed_in? %>
                                        <li class="nav-item nav-item-icon dropdown">
                                            <a class="nav-link" href="/carts/show">
                                                <i class="fa fa-shopping-bag"></i>
                                                <sup class="badge bg-base-1"><%=@current_cart.all_items%></sup>
                                            </a>

                                        <%= render "shared/cart" %>

                                        </li>
                                        <%end%>

                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>

app/views/shared/_recap_order.html.erb
<div class="row">
    <div class="col-12 col-md-6 col-lg-4 mt-2">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title mb-0">Information on recipient</h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Name: <%= @order.user_name %></li>
          <li class="list-group-item">Billing Address: <%= @order.billing_address %></li>
          <li class="list-group-item">Delivery Address: <%= @order.delivery_address %></li>
          <li class="list-group-item">Created on: <%= @order.created_at %></li>
          <% if @order.status %>
            <li class="list-group-item">Treated on: <%= @order.updated_at %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-8 mt-2">
      <div class="card">
        <div class="card-body">
          <table id="datatables-basic" class="table table-striped" style="width:100%">
            <thead>
              <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Size</th>
                <th>Quantity</th>
                <th>Subtotal</th>
              </tr>
            </thead>
            <tbody>
              <% @order.cart_items.each do |element| %>
                <tr>
                  <td><%= element.item.name %></td>
                  <td><%= element.item.final_price %>
                  <td><%= element.size.value %></td>
                  <td><%= element.quantity %></td>
                  <td class="product-total">
                    <div id="total-<%=element.id%>">
                      <span><%=number_to_currency(element.subtotal, unit:'$')%></span>
                      </div>
                  </td>
                <tr>
              <% end %>
            </tbody>
            <tfoot>
            </tfoot>
          </table>
          <div>
            <h3 class="mt-4">Total: <%= number_to_currency(@order.total, unit:'$') %></h3>
          </div>
        </div>
      </div>
    </div>
  </div>