config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'items/index', to: "items#index", as: "items_index"
  get 'items/:id/show', to: "items#show", as: "items_show"
  get 'items/filter', to: "items#filter", as: "items_filter"

  get 'carts/show'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: 'users/registrations' }

  resource :users do
    resources :orders, only: %i[new create index show]
  end

  devise_for :admins, controllers: { sessions: 'admins/sessions', confirmations: 'admins/confirmations', registrations: 'admins/registrations', passwords: 'admins/passwords', unlocks: 'admins/unlocks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  post 'cart_items/:item_id', to: "cart_items#create", as: "cart_items"
  delete 'cart_items/:id', to: "cart_items#destroy", as: "cart_items_destroy"
  post 'cart_items/:id/add_quantity', to: "cart_items#add_quantity", as: "cart_items_add"
  post 'cart_items/:id/reduce_quantity', to: "cart_items#reduce_quantity", as: "cart_items_reduce"
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :administration, only: [:index]

  namespace 'administration' do
    resources :items, only: %i[index create new destroy update edit]
    resources :orders, only: %i[index update edit show]
  end
end

app/models/cart.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: carts
#
#  id         :bigint(8)        not null, primary key
#  total      :decimal(, )      default(0.0)
#  user_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ApplicationRecord
  include CartTotal
  include ItemCount
  has_many :cart_items, as: :line_item, dependent: :destroy
  has_many :items, through: :cart_items
  belongs_to :user

  validates :user, presence: true, on: :create
  validates :total, presence: true, numericality: { greater_than_or_equal_to: 0 }, on: :create
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :check_user, only: :show

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    respond_to do |format|
      format.js { flash[:notice] = "Votre panier a bien été vidé" }
    end
  end

  protected

  def check_user
    redirect_to root_path unless user_signed_in?
  end
end

app/views/carts/show.html.erb
<section class="slice-xl page-title border-bottom has-bg-cover bg-size-cover">
    <div class="container mask-container">
        <div class="row">
            <div class="col-md-6">
                <div class="">
                    <h3 class="heading heading-1 strong-600 text-capitalize mb-1">
                    <span>Cart</span>
                    </h3>
                    <ol class="breadcrumb breadcrumb--style-2">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item"><a href="/items/index">Shop</a></li>
                        <li class="breadcrumb-item"><a href="#co">Checkout</a></li>
                    </ol>
                </div>
                <!-- Fluid text paragraph -->
                <div class="pb-4 mt-4">
                    <p class="lead">
                        Parturient mus aenean a suspendisse est ligula eu dui a ultricies dictumst porttitor rhoncus a vestibulum.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="slice sct-color-1">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 mt--150">
                <form class="form-default" data-toggle="validator" role="form">
                    <div class="card">
                        <div class="card-body">
                            <table class="table-cart">
                                <thead>
                                    <tr>
                                        <th class="product-image"></th>
                                        <th class="product-name">Product</th>
                                        <th class="product-size d-none d-lg-table-cell">Size</th>
                                        <th class="product-price d-none d-lg-table-cell">Price</th>
                                        <th class="product-quantity d-none d-md-table-cell">Quantity</th>
                                        <th class="product-total">Subtotal</th>
                                        <th class="product-remove"></th>
                                    </tr>
                                </thead>
                                <%@current_cart.cart_items.each do |cart_item|%>
                                <tbody>
                                    <tr class="cart-item" id="<%=cart_item.id%>">
                                        <td class="product-image">
                                             <%=image_tag cart_item.item.image_url, id: 'image_id'%>
                                        </td>
                                        <td class="product-name">
                                             <%=cart_item.item.name%>

                                        </td>
                                        <td class="product-size product-size d-none d-lg-table-cell">
                                            <span class="strong-600"><%=cart_item.size.value%></span>
                                        </td>
                                        <td class="product-price d-none d-lg-table-cell">
                                            <%=number_to_currency(cart_item.item.final_price, unit:'$')%>
                                        </td>
                                        <td class="product-quantity d-none d-md-table-cell">
                                           <div class="input-group input-group--style-2 pr-4" style="width: 130px;">
                                                <span class="input-group-btn">
                                                  <i class="ion-minus">
                                                  <%= link_to "-",cart_items_reduce_path(cart_item.id),remote: true, method: :post, class:"btn btn-number"%>
                                                  </i>
                                                </span>
                                                <div id="quantity-<%=cart_item.id%>" class="product-quantity pt-2">
                                                <%=cart_item.quantity%>
                                                </div>
                                                <span class="input-group-btn">
                                                  <i class="ion-plus">
                                                    <%= link_to "+",cart_items_add_path(cart_item.id),remote: true, method: :post, class:"btn btn-number"%>
                                                  </i>
                                                </span>
                                            </div>
                                        </td>
                                        <td class="product-total">
                                          <div id="total-<%=cart_item.id%>">
                                            <span><%=number_to_currency(cart_item.subtotal, unit:'$')%></span>
                                            </div>
                                        </td>
                                        <td class="product-remove">
                                            <a href="#" class="text-right pl-2">
                                                <i class="ion-trash-a">
                                                    <%= link_to "X",cart_items_destroy_path(cart_item.id), remote: true, method: :delete, class:"btn btn-number"%>
                                                </i>
                                            </a>
                                        </td>
                                    </tr>
                                  </tbody>
                                <%end%>          
                            </table>
                        </div>
                    </div>
                    <div>
                      <h3 class="mt-3">Total: <%= number_to_currency(@current_cart.tot, unit:'$') %></h3>
                    </div>      
                    <div class="row align-items-center pt-5">
                        <div class="col-6">
                            <a href="/" class="link link--style-3">
                                <i class="ion-android-arrow-back"></i>
                                Return to shop
                            </a>
                        </div>
                        <div class="col-6 text-right" id="co">
                            <%= link_to "Proceed to checkout", new_users_order_path, class: "btn btn-styled btn-base-1" %>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>