config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'items/index', to: "items#index", as: "items_index"
  get 'items/:id/show', to: "items#show", as: "items_show"
  get 'items/filter', to: "items#filter", as: "items_filter"

  get 'carts/show'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: 'users/registrations' }

  resource :users do
    resources :orders, only: %i[new create index show]
  end

  devise_for :admins, controllers: { sessions: 'admins/sessions', confirmations: 'admins/confirmations', registrations: 'admins/registrations', passwords: 'admins/passwords', unlocks: 'admins/unlocks' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  post 'cart_items/:item_id', to: "cart_items#create", as: "cart_items"
  delete 'cart_items/:id', to: "cart_items#destroy", as: "cart_items_destroy"
  post 'cart_items/:id/add_quantity', to: "cart_items#add_quantity", as: "cart_items_add"
  post 'cart_items/:id/reduce_quantity', to: "cart_items#reduce_quantity", as: "cart_items_reduce"
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :administration, only: [:index]

  namespace 'administration' do
    resources :items, only: %i[index create new destroy update edit]
    resources :orders, only: %i[index update edit show]
  end
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id                  :bigint(8)        not null, primary key
#  name                :string
#  image_url           :string
#  description         :text
#  price               :decimal(7, 2)
#  has_discount        :boolean          default(FALSE)
#  male                :boolean
#  female              :boolean
#  discount_percentage :integer          default(0)
#  category_id         :bigint(8)
#  brand_id            :bigint(8)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Item < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  has_many :cart_items, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :sizes, through: :stocks

  validates :price, presence: true, numericality: { greater_than: 0 }, on: :create
  validates :discount_percentage, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :name, presence: true, uniqueness: true, case_sensitive: false, format: { with: /\A[\x20-\x7E]+\z/, message: "Only alpha-numeric characters" }, length: { in: 3..30 }, on: :create
  validates :description, presence: true, length: { in: 10..500 }, on: :create
  validates :category, presence: true, on: :create
  validates :brand, presence: true, on: :create

  scope :alphabetical_order, -> { order(name: :asc) }
  scope :by_brand, ->(brand_id) { where brand_id: brand_id }
  scope :by_category, ->(category_id) { where category_id: category_id }

  def genre
    return "U" if male && female
    return "M" if male
    return "W" if female
  end

  def final_price
    has_discount ? (price * (1 - discount_percentage.to_f / 100)).round(2) : price
  end
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    after_action :update_discount, only: %i[create update]

    def index
      @items = Item.alphabetical_order
    end

    def new
      @item = Item.new
    end

    def edit
      @item = current_item
    end

    def create
      if @item = Item.create(item_params)
        redirect_to administration_items_path, notice: 'Item has beeen created'
      else
        redirect_to administration_items_path, notice: 'Item has not beeen created'
      end
    end

    def update
      @item = current_item
      if @item.update(item_params)
        redirect_to administration_items_path, notice: 'Item has been modified'
      else
        redirect_to administration_items_path, alert: "Item has not been modified"
      end
    end

    def destroy
      @item = current_item
      @item.destroy
      redirect_to administration_items_path, alert: "Item has been destroyed"
    end

    private

    def item_params
      params.require(:item).permit(:name, :image_url, :description, :price, :discount_percentage, :category_id, :brand_id, :male, :female)
    end

    def current_item
      Item.find(params[:id])
    end

    def update_discount
      if @item.discount_percentage.positive?
        @item.update(has_discount: true)
      else
        @item.update(has_discount: false)
      end
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.alphabetical_order
    @categories = Category.all
    @brands = Brand.all
  end

  def show
    @item = Item.find(params[:id])
    @sizes = Size.all
  end

  def filter
    @categories = Category.all
    @brands = Brand.all
    if params[:option].split(" ")[0] == "brand"
      @items = Item.by_brand(params[:option].split(" ")[1].to_i)
    elsif params[:option].split(" ")[0] == "category"
      @items = Item.by_category(params[:option].split(" ")[1].to_i)
      puts "--------SIMON--------"
      p @items
    end
  end
end

app/views/items/filter.html.erb
<section class="slice sct-color-1" id="sct_products">
    <div class="container">
        <div class="row">
            
            <div class="col-lg-9 order-lg-2">
                <div class="row-wrapper">
                
                    <div class="row cols-xs-space cols-sm-space cols-md-space">
                <% @items.each do |item| %>
                        <div class="col-lg-4">
                
                            <div class="block product bg-transparent no-radius">
                                <div class="product-image">
                                    <div class="view view-first">
                                      <img src="<%= item.image_url %>" alt="img shop"> 
                                    </div>

                                    <div class="product-actions--a product-actions--2" data-animation-in="slideInRight"  data-animation-out="slideOutRight">
                                        <button type="button" class="btn-product-action">
                                        <i class="ion-bag"></i>
                                        </button>
                                        
                                        <button type="button" class="btn-product-action">
                                        <i class="ion-ios-heart-outline"></i>
                                        </button>
                                    </div>

                                </div>
                    
                                <div class="block-body px-0">
                                    <h3 class="heading heading-6 strong-500 text-capitalize mb-0"><%= link_to item.name, items_show_path(item.id) %></h3>
                                    
                                    <div class="price-wrapper">
                                        <span class="price heading-6 c-gray-light strong-400"><span class="price-value"><%=number_to_currency( item.price, :unit=>'€') %></span></span>
                                    </div>
                                </div>
                            </div>

                        </div>
                <% end %>
                        
                    </div> 

                </div>

                <!-- Pagination -->
            </div>
            <div class="col-lg-3 order-lg-1">
                <div class="sidebar sidebar--style-4 b-lg-right">
                    
                    <!-- Product categories menu -->
                    <div class="sidebar-object b-xs-bottom pb-4 mb-4">
                        <h2 class="sidebar-object-title">
                        <span>Categories</span>
                        </h2>
                         
                        <div class="filter-checkbox">
                        <% @categories.each do |cat| %>
                          <%= form_tag items_filter_path, method: :get do %>
                            <%= radio_button_tag :option,["category", cat.id], false, id:"chkFilterCategoryWomen", onclick: "this.form.submit();"%>
                            <%=label_tag  cat.name %>
                          <%end%>
                        <% end %>
                        </div>
                    </div>
                     <!-- Filter by size -->
                    <div class="sidebar-object b-xs-bottom pb-4 mb-4">
                        <h2 class="sidebar-object-title">
                        <span>Filter</span> by size
                        </h2>
                        <ul class="list-inline checkbox-alphanumeric">
                            <li>
                                <input type="radio" id="size-1" name="size">
                                <label for="size-1">S</label>
                            </li>
                            <li>
                                <input type="radio" id="size-2" name="size">
                                <label for="size-2">M</label>
                            </li>
                            <li>
                                <input type="radio" id="size-3" name="size" checked="">
                                <label for="size-3">L</label>
                            </li>
                            <li>
                                <input type="radio" id="size-4" name="size">
                                <label for="size-4">XL</label>
                            </li>
                        </ul>
                    </div>
                    
                    <!-- Filter by material -->
                    <div class="sidebar-object b-xs-bottom pb-4 mb-4">
                        <h2 class="sidebar-object-title">
                        <span>Filter by brand</span>
                        </h2>
                        <div class="filter-checkbox">
                        <% @brands.each do |brand| %>
                          <%= form_tag items_filter_path, method: :get do %>
                            <%= radio_button_tag :option, ["brand", brand.id], false, onclick: "this.form.submit();"%>
                            <%=label_tag  brand.name %>
                           <% end%>
                        <% end %>
                        </div>
                    </div>
                            
                        </div>
                    </div>
        </div>
    </div>
</section>

app/views/items/index.html.erb
<section class="slice sct-color-1" id="sct_products">
    <div class="container">
        <div class="row">
            
            <div class="col-lg-9 order-lg-2">
                <div class="row-wrapper">
                
                    <div class="row cols-xs-space cols-sm-space cols-md-space">
                <% @items.each do |item| %>    
                        <div class="col-lg-4">
                
                            <div class="block product bg-transparent no-radius">
                                <div class="product-image">
                                    <div class="view view-first">
                                      <img src="<%= item.image_url %>" alt="img shop"> 
                                    </div>

                                    <div class="product-actions--a product-actions--2" data-animation-in="slideInRight"  data-animation-out="slideOutRight">
                                        <button type="button" class="btn-product-action">
                                        <i class="ion-bag"></i>
                                        </button>
                                        
                                        <button type="button" class="btn-product-action">
                                        <i class="ion-ios-heart-outline"></i>
                                        </button>
                                    </div>

                                </div>
                    
                                <div class="block-body px-0">
                                    <h3 class="heading heading-6 strong-500 text-capitalize mb-0"><%= link_to item.name, items_show_path(item.id) %></h3>
                                    
                                    <div class="price-wrapper">
                                        <span class="price heading-6 c-gray-light strong-400"><span class="price-value"><%=number_to_currency( item.price, :unit=>'€') %></span></span>
                                    </div>
                                </div>
                            </div>

                        </div>
                <% end %>
                        
                    </div> 

                </div>

                <!-- Pagination -->
            </div>
            <div class="col-lg-3 order-lg-1">
                <div class="sidebar sidebar--style-4 b-lg-right">
                    
                    <!-- Product categories menu -->
                    <div class="sidebar-object b-xs-bottom pb-4 mb-4">
                        <h2 class="sidebar-object-title">
                        <span>Categories</span>
                        </h2>
                         
                        <div class="filter-checkbox">
                        <% @categories.each do |cat| %>
                          <%= form_tag items_filter_path, method: :get do %>

                              <%= radio_button_tag :option, ["category", cat.id], false, onclick: "this.form.submit();"%>
                               <%=label_tag  cat.name %>
                          <%end%>
                        <% end %>
                        </div>
                    </div>
                    
                    <!-- Filter by material -->
                    <div class="sidebar-object b-xs-bottom pb-4 mb-4">
                        <h2 class="sidebar-object-title">
                        <span>Filter by brand</span>
                        </h2>
                        <div class="filter-checkbox">
                        <% @brands.each do |brand| %>
                          <%= form_tag items_filter_path, method: :get do %>
                            <%= radio_button_tag :option, ["brand", brand.id], false, onclick: "this.form.submit();"%>
                             <%=label_tag  brand.name %>
                          <%end%>
                         <% end %>
                        </div>
                    </div>
                            
                        </div>
                    </div>
        </div>
    </div>
</section>

app/views/items/show.html.erb
<section class="slice bg-minimalist">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <img src="<%= @item.image_url %>" alt="img shop" class="pl-5">
            </div>
            <div class="col-lg-5 ml-lg-auto">
                <div class="product-description-wrapper">
                    <!-- Product title -->
                    <h2 class="heading heading-4 strong-600 text-capitalize">
                    <%= @item.name %>
                    </h2>
                    <span class="heading heading-light heading-5 strong-600 mt-3">
                    <%= number_to_currency( @item.price, :unit=>'$') %>
                    </span>
                    <span class="space-xs-md"></span>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-default">
                               <%= form_for @item, url: cart_items_path(@item), method: :post, remote: true do |f|%>
                                        <div class="product-short-text">
                                            <p>
                                                <%= @item.description %>
                                            </p>
                                        </div>
                                <div class="row mb-3 mt-2">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                          <%= f.collection_select :size_ids, Size.all, :id, :value, class:"form-control select2"%>
                                       </div>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                <% if user_signed_in? %>
                                    <div class="col-12">
                                        <!-- Add to cart button -->
                                        <%=f.submit 'Add to cart',class: "btn btn-lg btn-block btn-gray-dark btn-icon-left" %>
                                        <% end %>
                                    </div>
                               <%end%>
                                </div>
                            </div>
                        </div>
                    </div>
                    <% unless user_signed_in? %>
                    <%= button_to "Connect to order", new_user_session_path, method: :get, class: "btn btn-lg btn-block btn-gray-dark btn-icon-left" %>
                    <% end %>
                    <span class="space-xs-md"></span>
                </div>
            </div>
        </div>
    </div>
</section>